Add integration testing loan escrow
debtdao/smart-contracts pull request #44
Opened 2022-04-11 05:12 UTC by James-Sangalli

Closes #43 

This PR:

1. Creates a loan contract that inherits `BaseLoan` & `EscrowedLoan`
2. Performs integration tests between the loan contract and the escrow contract

2022-04-12 03:15 UTC, kibagateaux requested changes

2022-04-12 03:15 UTC, kibagateaux commented on contracts/modules/loan/Loan.t.sol
> +        loan.liquidate(positionId, 1 ether, address(supportedToken1));
ok this shouldn't be possible. thnx for reminding me I forgot to add the healthcheck in borrow() function to make sure loan is valid

2022-04-12 03:15 UTC, kibagateaux commented on contracts/modules/loan/Loan.t.sol
> +        loan.liquidate(positionId, 1 ether, address(supportedToken1));
#50 created

2022-04-12 03:15 UTC, kibagateaux commented on contracts/modules/loan/Loan.t.sol
> +        assert(loan.healthcheck() == LoanLib.STATUS.LIQUIDATABLE);
ok once i fix the above then we'll need to reduce price of collateral after line 66 before we check if price is liquidatable

2022-04-12 03:15 UTC, kibagateaux commented on contracts/modules/loan/Loan.t.sol
> +        escrow.addCollateral(1 ether, address(supportedToken1));
You're using `supportedToken1` for all the loans so can you use `supportedToken2` for collateral? i dont think it affects current tests and i can't think of other tests to add for now but I can see that being a requirement for some tests in the future

2022-04-12 03:15 UTC, kibagateaux commented on contracts/modules/loan/Loan.t.sol
> +}
Can you add two tests for 
1) tokens are transferred out of escrow and 
2) tokens are sent to sender of liquidate function (address(this)

We technically test this in Escrow tests already but we will add in new liquidation logic (thats why i made it virtual internal func so we can override) so want to ensure that specific implementations of Loan do what they are expected on top of Escrow's base functionality

2022-04-13 06:49 UTC, James-Sangalli commented
@kibagateaux PR is ready but two of the tests fail because of https://github.com/debtdao/smart-contracts/issues/52

2022-04-16 08:12 UTC, kibagateaux commented
This is a great start. Ready to merge in but have 1 question on changing `_accrueInterest` to virtual. There's already a hook for `_getInterestPaymentAmount`, can you override that to always return 0 instead of overriding `_accrueInterest` directly? I'm trying to differentiate "process" vs "implementation" with the different internal functions. The ones that i dont currently have as virtual at the bottom of the BaseLoan.sol file are "process" and shouldn't need to change for any loan type while the "implementation" internal functions that are virtual/override (aka hooks) may will change per loan type but will still fall in the same process flow.

Also can you change test file name from `Loan.t.sol` to `EscrowedLoan.t.sol`.

Other than those two small changes looks good to merge in

2022-04-17 05:33 UTC, James-Sangalli commented on contracts/modules/loan/RevolverLoan.sol
> +      (, uint256 accruedTokenValue) = _accrueInterest(positionIds[i]);
@kibagateaux also fixed this.

2022-04-17 05:33 UTC, James-Sangalli commented
> This is a great start. Ready to merge in but have 1 question on changing `_accrueInterest` to virtual. There's already a hook for `_getInterestPaymentAmount`, can you override that to always return 0 instead of overriding `_accrueInterest` directly? I'm trying to differentiate "process" vs "implementation" with the different internal functions. The ones that i dont currently have as virtual at the bottom of the BaseLoan.sol file are "process" and shouldn't need to change for any loan type while the "implementation" internal functions that are virtual/override (aka hooks) may will change per loan type but will still fall in the same process flow.
> 
> Also can you change test file name from `Loan.t.sol` to `EscrowedLoan.t.sol`.
> 
> Other than those two small changes looks good to merge in

Done.

2022-04-18 04:47 UTC, kibagateaux commented
Ok one last thing. I ran the tests and `test_health_becomes_liquidatable_if_cratio_below_min` + test_can_liquidate_escrow_if_cratio_below_min` both fail with error "Loan: can't borrow". I think the issue is we aren't setting the oracle price for the assets in `setUp` function so collateral value is 0 even though we've already deposited.

I think adding `oracle.changePrice(supportedToken2, 10)` on after line 33 oracle is deployed (or after line 37 when we deposit collateral) should fix both tests.

2022-04-18 05:53 UTC, James-Sangalli commented
> Ok one last thing. I ran the tests and `test_health_becomes_liquidatable_if_cratio_below_min` + test_can_liquidate_escrow_if_cratio_below_min`both fail with error "Loan: can't borrow". I think the issue is we aren't setting the oracle price for the assets in`setUp` function so collateral value is 0 even though we've already deposited.
> 
> I think adding `oracle.changePrice(supportedToken2, 10)` on after line 33 oracle is deployed (or after line 37 when we deposit collateral) should fix both tests.

@kibagateaux `test_health_becomes_liquidatable_if_cratio_below_min` should fail because of #52, the collateral value function in `Escrow` scales them by decimal but the loan contract does not, resulting in a massive value mismatch. 

The prices are actually set in the `SimpleOracle` constructor for simplicity: https://github.com/debtdao/smart-contracts/blob/master/contracts/mock/SimpleOracle.sol#L11

`test_can_liquidate_escrow_if_cratio_below_min` fails because of #53, the `Escrow` contract calls `accrueInterest` & `accrueInterest` calls `isActive`. This reverts because the loan is liquidatable, thereby preventing the liquidation from happening.  

I ran the tests with the decimals scaled and `isActive` removed and they pass, essentially these tests are doing their job by failing.  

I will need to make separate PRs for those two issues but they do not invalidate this PR.

2022-04-18 11:17 UTC, kibagateaux commented
Factuals ok. I've actually been considering for a while if the isActive checks should be taken off the internal functions. We can handle that separately.

2022-04-18 11:17 UTC, merged